---
- name: Validate variables.
  ansible.builtin.assert:
    that:
      - "'laravel' == app_type"

- name: Import action tasks.
  ansible.builtin.import_tasks: install.yml
  become_user: "{{ app_user }}"
  become: true
